logging:
  version: 1
  formatters:
    etl:
      format: "\n--- %(levelname)s ---\nName = %(name)s | Process = %(process)d | %(asctime)s\n%(message)s\n"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: etl
      stream: ext://sys.stdout
  loggers:
    sampleLogger:
      level: DEBUG
      handlers: [console]
      propagate: no
  root:
    level: DEBUG
    handlers: [console]