"""fact_vaccinations_by_nis_code_daily_updated

Revision ID: 7e4a579fbad8
Revises: d7fd1832e0dd
Create Date: 2021-11-15 15:49:36.898337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4a579fbad8'
down_revision = 'd7fd1832e0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_vaccinations_by_nis_code_daily_updated',
    sa.Column('nis_code', sa.String(length=5), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('agegroup', sa.String(), nullable=False),
    sa.Column('plus18', sa.Boolean(), nullable=False),
    sa.Column('plus65', sa.Boolean(), nullable=False),
    sa.Column('vaccinated_fully_total', sa.Integer(), nullable=False),
    sa.Column('vaccinated_partly_total', sa.Integer(), nullable=False),
    sa.Column('vaccinated_fully_astrazeneca', sa.Integer(), nullable=False),
    sa.Column('vaccinated_partly_astrazeneca', sa.Integer(), nullable=False),
    sa.Column('vaccinated_fully_pfizer', sa.Integer(), nullable=False),
    sa.Column('vaccinated_partly_pfizer', sa.Integer(), nullable=False),
    sa.Column('vaccinated_fully_moderna', sa.Integer(), nullable=False),
    sa.Column('vaccinated_partly_moderna', sa.Integer(), nullable=False),
    sa.Column('vaccinated_fully_johnsonandjohnson', sa.Integer(), nullable=False),
    sa.Column('vaccinated_fully_other', sa.Integer(), nullable=False),
    sa.Column('vaccinated_partly_other', sa.Integer(), nullable=False),
    sa.Column('population_by_agecategory_and_municipality', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nis_code', 'sex', 'agegroup', 'plus18', 'plus65')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_vaccinations_by_nis_code_daily_updated')
    # ### end Alembic commands ###
