"""fact_covid_vaccinations_by_category

Revision ID: 218262db97ee
Revises: 522d837cbaa1
Create Date: 2021-11-14 23:54:13.304062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218262db97ee'
down_revision = '522d837cbaa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_covid_vaccinations_by_category',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('agegroup', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'region', 'agegroup', 'sex', 'brand', 'dose')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_covid_vaccinations_by_category')
    # ### end Alembic commands ###
